"""Add raw_request to PANVerification

Revision ID: 72312331df5b
Revises: e2f3a4b5c6d7
Create Date: 2026-09-08 21:30:47.151556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72312331df5b'
down_revision = 'e2f3a4b5c6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pan_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_request', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pan_verifications', schema=None) as batch_op:
        batch_op.drop_column('raw_request')

    # ### end Alembic commands ###
